site_name: AWS Edge Services Workshops 
site_description: 'A collection of AWS Edge Services Labs that allow diferent workshops'
site_url: 'https://edgeservices-workshops.builder-culture.com'

# Repository
repo_name: 'builder-culture/edgeservices-workshops'
repo_url: 'https://github.com/builder-culture/edgeservices-workshops'

google_analytics: 
    - 'UA-166774903-1'
    - auto 

# Copyright
copyright: '&copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Must use true for gh-deploy
#use_directory_urls: true

# Must use for /site builds
# NOTE: will break gh-deploy
#use_directory_urls: false
plugins:
    - search:
        separator: '[\s\-\.]+'
        lang:
            - en
            - es
            - pt
            - de
    - minify:
        minify_html: true
    - git-revision-date-localized:
        type: date   

markdown_extensions:
    - admonition
    - footnotes
    - codehilite:
        linenums: true
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed
    - pymdownx.tilde

theme:
    name: material
    palette:
        primary: orange
        accent: yellow
    icon:
        logo: fontawesome/brands/aws
    features:
        - tabs
        - instant
    language: en
    favicon: assets/images/favicon.ico
    highlights: true
    hljs_langauages:
        - html
        - yaml
        - javascript
        - python
        - htmlbars

nav:
    - Home: README.md

    - CloudFront:
        - Overview: 'CloudFront/README.md'
        - Accelerate your content:
            - Lab Overview: 'CloudFront/Accelerate_your_content/README.md'
            - Lab Guide: 'CloudFront/Accelerate_your_content/Lab_Guide.md'
            - Go further: 'CloudFront/Accelerate_your_content/Lab_Bonus.md'
            - Troubleshooting: 'CloudFront/Accelerate_your_content/Troubleshooting.md'
    
    - Lambda@Edge:
        - Overview: 'LambdaAtEdge/README.md'
        - Generate content dynamically:
            - Lab Overview: 'LambdaAtEdge/Generate_content_dynamically/README.md'
            - Lab Guide: 'LambdaAtEdge/Generate_content_dynamically/Lab_Guide.md'
            - Troubleshooting: 'LambdaAtEdge/Generate_content_dynamically/Troubleshooting.md'
             
    - S3 Transfer Acceleration:
        - Overview: 'S3-TransferAcceleration/README.md'

    - WAF:
        - Overview: 'WAF/README.md'
        - Perimeter protection:
            - Lab Overview: 'WAF/Perimeter_protection/README.md'
            - Lab Guide: 'WAF/Perimeter_protection/Lab_Guide.md'
            - Troubleshooting: 'WAF/Perimeter_protection/Troubleshooting.md'
    
#    - Shield:
#        - Overview: 'Shield/README.md'

    - More AWS Resources:
        - Entries: 'MoreResources/README.md'

    - About: about.md